### ISSUE TITLE
Can't get v1.1.1 to work - rolled back to v1.1.0 [Windows 10]

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#16]
I did the official uninstall, deleted the following folders as well in order to do a clean install:
`C:\Users\UserName\AppData\Local\parsify-desktop-updater`
`C:\Users\UserName\AppData\Roaming\Parsify Desktop`
The installation of `v1.1.1` seems to happen, but when launching, I get this error:

<details>
<summary>A JavaScript error occurred in the main process</summary>

```
Uncaught Exception:
Error: Something went wrong during the migration! Changes applied to the store until this failed migration will be restored. TypeError: Use `delete()` to clear values
    at ElectronStore._migrate (C:\Users\UserName\AppData\Local\Programs\parsify-desktop\resources\app.asar\node_modules\conf\index.js:228:11)
    at new Conf (C:\Users\UserName\AppData\Local\Programs\parsify-desktop\resources\app.asar\node_modules\conf\index.js:141:9)
    at new ElectronStore (C:\Users\UserName\AppData\Local\Programs\parsify-desktop\resources\app.asar\node_modules\electron-store\index.js:23:3)
    at Module.<anonymous> (C:\Users\UserName\AppData\Local\Programs\parsify-desktop\resources\app.asar\app\background.js:1:2792)
    at t (C:\Users\UserName\AppData\Local\Programs\parsify-desktop\resources\app.asar\app\background.js:1:124)
    at C:\Users\UserName\AppData\Local\Programs\parsify-desktop\resources\app.asar\app\background.js:1:923
    at Object.<anonymous> (C:\Users\UserName\AppData\Local\Programs\parsify-desktop\resources\app.asar\app\background.js:1:933)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

</details>

The app window doesn't appear, but looking at the task manager, there are some background processes of _Parsify_ running.
So, I uninstalled `v1.1.1` and did the same steps as mentioned before, installed `v.1.1.0` again, which does work. 🤷‍♂️

Thanks

**Comment by xxczaki** [comment]
@LarsJandel The error message is fortunately relatively clear now, there has been an issue with the storage migration module (the one, which stores user configuration). Version `1.1.2` will contain a fix and will be released in less than an hour.

**Comment by xxczaki** [comment]
Done. Also, I changed the auto-updater endpoint in this release, so while the auto-updater might work, I recommend doing a manual installation,

**Comment by LarsJandel** [comment]
Just tested, installed just fine. Thanks!

// edit: issue below resolved - I have an odd firewall running on my work station which blocked the licensing 🤦‍♂️ - _works now everywhere_ 🎉
License question: I am using _Parsify_ on my laptop and my work station and now I can't get the license to work on my work station anymore. I had the impression, it worked on both machines before. It should, right → `Unlimited activations`? Thanks.
Okay, tested on my rarely used MacBook as well and the license works there too, must be an issue with my work station I guess.
