### ISSUE TITLE
Update error on waking pc

### ISSUE THREAD

**Issue by ecciv** [parsify-dev/desktop#29]
When I wake my PC from sleep in the morning the following error message pops up.

"Unhandled Promise Rejection
Error: Unable to find latest version on GitHub (https://api.github.com/repos/parsify-dev/desktop/releases/latest), please ensure a production release exists: Error: net::ERR_NETWORK_IO_SUSPENDED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2575:21)
    at newError (C:/Users/Victor/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/builder-util-runtime/out/index.js:212:17)
    at PrivateGitHubProvider.getLatestVersionInfo (C:/Users/Victor/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/providers/PrivateGitHubProvider.js:146:48)
    at async PrivateGitHubProvider.getLatestVersion (C:/Users/Victor/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/providers/PrivateGitHubProvider.js:90:25)
    at async NsisUpdater.getUpdateInfoAndProvider (C:/Users/Victor/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:487:13)
    at async NsisUpdater.doCheckForUpdates (C:/Users/Victor/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:503:20)
    at async Timeout._onTimeout (C:/Users/Victor/AppData/Local/Programs/parsify-desktop/resources/app.asar/app/background.js:1:3707)"

**Comment by ecciv** [comment]
Oops, sorry, same as #7. I'm on 1.2.2.

**Comment by xxczaki** [comment]
Yes, follow #7 on that. Unfortunately, there is nothing I can do about this issue at the moment, the current, external auto-updating system is a bit broken and I'm trying to find a better solution as a replacement ;)
