### ISSUE TITLE
Omit update error on network disconnection, e.g. machine going to sleep

### ISSUE THREAD

**Issue by LarsJandel** [parsify-dev/desktop#7]
When I close my laptop, putting it to sleep, I will get an update error, when starting it up again. Maybe you can omit this warning. Thanks.
<details>
<summary>Unhandled Promise Rejection</summary>

```Unhandled Promise Rejection
Error: Unable to find latest version on GitHub (https://api.github.com/repos/xxczaki/desktop/releases/latest), please ensure a production release exists: Error: net::ERR_NETWORK_IO_SUSPENDED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2571:21)
    at newError (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/builder-util-runtime/out/index.js:212:17)
    at PrivateGitHubProvider.getLatestVersionInfo (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/providers/PrivateGitHubProvider.js:146:48)
    at async PrivateGitHubProvider.getLatestVersion (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/providers/PrivateGitHubProvider.js:90:25)
    at async NsisUpdater.getUpdateInfoAndProvider (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:487:13)
    at async NsisUpdater.doCheckForUpdates (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:503:20)
    at async Timeout._onTimeout (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/app/background.js:1:3851)

**Comment by xxczaki** [comment]
This issue should not occur anymore due to recent auto-update changes.

**Comment by LarsJandel** [comment]
Well, just had the identical error again, when I woke my laptop 🤷‍♂️
I did a manual install of v1.2.0:
- used the official uninstaller
- deleted the updater folder
- deleted everything in the roaming folder except for the license

[Parsify v1.2.0 | Windows 10]

**Comment by xxczaki** [comment]
@LarsJandel Is the URL address in the error the same as before (https://api.github.com/repos/xxczaki/desktop/releases/latest) or not?

**Comment by LarsJandel** [comment]
Looks identical to me:
`Error: Unable to find latest version on GitHub (https://api.github.com/repos/parsify-dev/desktop/releases/latest), please ensure a production release exists: Error: net::ERR_NETWORK_IO_SUSPENDED`

**Comment by xxczaki** [comment]
@LarsJandel `1.2.1` should hopefully fix this. However, auto-updating is a difficult thing, especially when you are dealing with 3 platforms at once.

**Comment by LarsJandel** [comment]
Thanks, will install it tomorrow. Good night! 😴

**Comment by LarsJandel** [comment]
Installed yesterday morning, it was looking good including some sleep and wake actions for the laptop, but the error just popped again, when I woke it this morning - sorry...
<details>
<summary>Unhandled Promise Rejection</summary>

```
Error: Unable to find latest version on GitHub (https://api.github.com/repos/parsify-dev/desktop/releases/latest), please ensure a production release exists: Error: net::ERR_NETWORK_IO_SUSPENDED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2571:21)
    at newError (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/builder-util-runtime/out/index.js:212:17)
    at PrivateGitHubProvider.getLatestVersionInfo (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/providers/PrivateGitHubProvider.js:146:48)
    at async PrivateGitHubProvider.getLatestVersion (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/providers/PrivateGitHubProvider.js:90:25)
    at async NsisUpdater.getUpdateInfoAndProvider (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:487:13)
    at async NsisUpdater.doCheckForUpdates (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:503:20)
    at async Timeout._onTimeout (C:/Users/UserName/AppData/Local/Programs/parsify-desktop/resources/app.asar/app/background.js:1:3595)
```

</details>

**Comment by xxczaki** [comment]
With the update system changed in one of the recent releases, this should no longer occur. While the auto-updating currently only works on Windows (AFAIK), macOS support should be added before the end of the year, as I'm planning on finally buying the Apple Developer License and code-signing Parsify on Mac :smile:
